// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPCYlS6b1hwP3BKuRMUpFDTL8ZSU4OPI',
    appId: '1:990473126637:web:7aeb0b57f7e769ca49c2e4',
    messagingSenderId: '990473126637',
    projectId: 'jaano-1327f',
    authDomain: 'jaano-1327f.firebaseapp.com',
    storageBucket: 'jaano-1327f.firebasestorage.app',
    measurementId: 'G-SL4P2LPSDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClD0onRwNj6aCrDyO70zFp7k9AsBy7p3o',
    appId: '1:990473126637:android:ba0b8e2048361b7649c2e4',
    messagingSenderId: '990473126637',
    projectId: 'jaano-1327f',
    storageBucket: 'jaano-1327f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADZZ1tGa2v4jog3JuXDOuoxrx7OGDXTro',
    appId: '1:990473126637:ios:e189c4c7d3774fdf49c2e4',
    messagingSenderId: '990473126637',
    projectId: 'jaano-1327f',
    storageBucket: 'jaano-1327f.firebasestorage.app',
    iosBundleId: 'com.example.jaanoArticlesScripe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADZZ1tGa2v4jog3JuXDOuoxrx7OGDXTro',
    appId: '1:990473126637:ios:e189c4c7d3774fdf49c2e4',
    messagingSenderId: '990473126637',
    projectId: 'jaano-1327f',
    storageBucket: 'jaano-1327f.firebasestorage.app',
    iosBundleId: 'com.example.jaanoArticlesScripe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMHIYB7iXT6bJvl_uzTOpStJ9n6GLWwS4',
    appId: '1:990473126637:web:8a60c731b21408de49c2e4',
    messagingSenderId: '990473126637',
    projectId: 'jaano-1327f',
    authDomain: 'jaano-1327f.firebaseapp.com',
    storageBucket: 'jaano-1327f.firebasestorage.app',
    measurementId: 'G-YTX3H66NEF',
  );
}
